### ISSUE TITLE
Send Quotes from known Authors only

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [FotieMConstant/geek-quote-api#10]
Ability to request quotes from authors who are not _`unknown author`_

**Comment by rohit267** [comment]
please look into my PR

**Comment by FotieMConstant** [comment]
Hey, @rohit267. just checked and merged your PR. thanks for the great work.
@Rishabh-malhotraa your issue has been solved!

**Comment by FotieMConstant** [comment]
I'm closing this issue!
