### ISSUE TITLE
Endpoint to get quotes related to a particular keyword 

### ISSUE THREAD

**Issue by FotieMConstant** [FotieMConstant/geek-quote-api#2]
I think we need an endpoint that will return quotes related to a particular keyword or something.

**Comment by sudo-which-qp** [comment]
explain more on this

**Comment by FotieMConstant** [comment]
Sure, for example, one should be able to request **https://geek-quote-api.herokuapp.com/v1/quote/filter/{{keyword}}**
When you pass a keyword as param... You should get a generated list of quotes having that keyword. 

e.g  **https://geek-quote-api.herokuapp.com/v1/quote/filter/Microsoft** should return:
```json
{
  "quote":"Microsoft: You’ve got questions. We’ve got dancing paperclips.",
  "author":"Unknown Author"
}
```
Note: This could return all or a specific number of random related quotes...

**Comment by sudo-which-qp** [comment]
Nice... will see what I can do

**Comment by FotieMConstant** [comment]
> Nice... will see what I can do

Awesome... thanks man

**Comment by FotieMConstant** [comment]
Hey @quiet-programmer how about we have it return all the possible matches of the keyword, like for example. if I pass a keyword "code" it returns all the quotes that match the keyword in an array.

**Comment by sudo-which-qp** [comment]
I tot of doing that, but just decided to do for single quotes first

**Comment by sudo-which-qp** [comment]
> I tot of doing that, but just decided to do for single quotes first

I Will work on that too... Thanks for accepting PR again

**Comment by sudo-which-qp** [comment]
@FotieMConstant  I think this issue should be closed
